### PR TITLE
Allow more flexible join conditions

### PR DESCRIPTION
**Pull request by Al2Klimov**
* [x] description
* [x] tests
  * [x] #12

### CODE REVIEW

**Comment by Al2Klimov** [comment]
I'd like to update tests instead of adding ones, but that would require #12.

**Comment by lippserd** [comment]
PR #12 depends on the deep clone PR which is not yet updated.

**Comment by lippserd** [comment]
Also, there's PHPDoc missing for the added $operator parameter.

**Comment by Al2Klimov** [comment]
Damn. Elephant oversight. Sorry!

**Comment by Al2Klimov** [comment]
> PR #12 depends on the deep clone PR which is not yet updated.

No, [it doesn't](https://github.com/Icinga/ipl/pull/5#pullrequestreview-99739823).

**Pull request merged**
